;You need to edit line 5 and 9. Don't edit line 34, unless you hate us, then.. go ahead.
<!DOCTYPE html>
<html>
<head>
	<title>Stats generated by #YOURCHANNEL</title>
	<link rel="stylesheet" type="text/css" href="dark-style.css">
</head>
<body>
<h1 class="center">Stats generated by #YOURCHANNEL</h1>
<table>
<tr>
	<th>Channel</th>
	<th>Last updated</th>
	<th>Users</th>
</tr>
<?php

$cache = file_get_contents("index-cache.txt") or die("Cache file not found!");
$channels = explode("\n", $cache);

foreach ($channels as $channel) {
	$data = explode("\001", $channel);
	echo '<tr onclick="document.location = \'' . $data[0] . '\'">';
	echo '<td>' . $data[1] . '</td>';
	echo '<td>' . $data[2] . '</td>';
	echo '<td>' . $data[3] . '</td>';
	echo '</tr>';
}

?>

</table>

<h6 class="center">pisg!stats@pisg/stats/bot @ freenode | Generated by <a href="https://github.com/PISG/pisg">PISG</a> | All rights reserved</h6>
</body>
</html>
